In [19]:
import numpy as np
def F(x, f): 
    f[0]=x[0]*x[0]+x[0]*x[1]-10.
    f[1]=x[1]+3.*x[0]*x[1]*x[1]-57.
    return f

def dF(x):
    df[0,0] = 2.*x[0]+x[1]
    df[0,1] = x[0]
    df[1,0] = 3.*x[1]**2
    df[1,1] = 1.+6.*x[0]*x[1]
    return df

x = np.array([0,1])
f = np.array([0,0])
df= np.array([[0,0],[0,0]])
print("F(x)=" , F(x))
print("dF(x)=" , dF(x))

F(x)= [-10 -56]
dF(x)= [[1 0]
 [3 1]]


In [23]:
from numpy import *
from numpy.linalg import solve

n = 2
eps = 1e-3
deriv = zeros( (n, n), float)
f = zeros( (n), float)
x = array([0.5, 0.5])

def F(x, f): 
    f[0]=x[0]*x[0]+x[0]*x[1]-10.
    f[1]=x[1]+3.*x[0]*x[1]*x[1]-57.
    
def dFi_dXj(x, deriv, n):                           # Derivatives
    h = 1e-4                                             
    for j in range(0, n):
         temp = x[j]
         x[j] = x[j] +  h/2.
         F(x, f)                                                 
         for i in range(0, n):  deriv[i, j] = f[i] 
         x[j] = temp
    for j in range(0, n):
         temp = x[j]
         x[j] = x[j] - h/2.
         F(x, f)
         for i in range(0, n): deriv[i, j] = (deriv[i, j] - f[i])/h
         x[j] = temp

for it in range(1, 100):                            
      F(x, f)                              
      dFi_dXj(x, deriv, n)   
      B = array([[-f[0]], [-f[1]]])      
      sol = solve(deriv, B)
      dx = sol#take(sol, (0, ), 1)               # First column of sol
      for i in range(0, n):
        x[i]  = x[i]  +  dx[i]
      errX = errF = errXi = 0.0
      endi=0
      for i in range(0, n):
        if ( x[i] !=  0.): errXi = abs(dx[i]/x[i])
        else:  errXi = abs(dx[i])
        if ( errXi > errX): errX = errXi                            
        if ( abs(f[i]) > errF ):  errF = abs(f[i])        
        if ( (errX <=  eps) and (errF <=  eps) ): endi=1
      if(endi==1): break  
      
print('Number of iterations = ', it, "\n Final Solution:")
for i in range(0, n):
        print('x[', i, '] =  ', x[i])        


Number of iterations =  15 
 Final Solution:
x[ 0 ] =   2.0
x[ 1 ] =   3.00005


In [24]:
print(np.zeros(4))

[ 0.  0.  0.  0.]


In [25]:
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])
c=np.zeros(4)

for i in range(4):
    for j in range(4):
        # please finish this line
        c[i]=c[i]+a[i,j]*b[j]
        
print(c)

[ 232.  218.  123.  213.]


In [26]:
import numpy as np
#============================================================================
def LUFactor(a, ipivot, n):
# Copy right, code from Titus textbook. 
#----------------------------------------------------------------------------
#  Performs LU factorization of (n x n) matrix a (diag(L) = 1). On exit,
#  replaces upper triangle and diagonal with U, and lower triangle, with L.
#  Uses partial pivoting on columns.
#  a      - coefficient matrix (n x n); LU decomposition on exit
#  ipivot - array of pivot row indexes (output)
#  det    - determinant of coefficient matrix (output).
#----------------------------------------------------------------------------
   det = 1e0
   for j in range(n):                                 # loop over columns
      for i in range(j):                             # elements of matrix U
         sum = a[i][j]
         for k in range(i): sum -= a[i][k]*a[k][j]
         a[i][j] = sum

      amax = 0e0
      for i in range(j,n):                           # elements of matrix L
         sum = a[i][j]                                 # undivided by pivot
         for k in range(j): sum -= a[i][k]*a[k][j]
         a[i][j] = sum
                                                            # determine pivot
         if (amax < np.fabs(a[i][j])): amax = np.fabs(a[i][j]); imax = i

      if (amax == 0e0): print("LUFactor: singular matrix !"); return 0e0

      ipivot[j] = imax                                # store pivot row index
                                                # interchange rows imax and j
      if (imax != j):                           # to put pivot on diagonal
         det = -det
         for k in range(n):
            t = a[imax][k]; a[imax][k] = a[j][k]; a[j][k] = t

      det *= a[j][j]                        # multiply determinant with pivot

      t = 1e0/a[j][j]                         # divide elements of L by pivot
      for i in range(j+1,n): a[i][j] *= t

   return det

#============================================================================
def LUSystem(a, ipivot, b, n):
# Copy right, code from Titus textbook. 
#----------------------------------------------------------------------------
#  Solves linear system a x = b of order n by LU factorization.
#  a      - LU decomposition of coefficient matrix (returned by LUFactor)
#  ipivot - array of pivot row indexes (input)
#  b      - vector of constant terms (input); solution x (on exit)
#----------------------------------------------------------------------------
   for i in range(n):                                     # solves Ly = b
      sum = b[int(ipivot[i])]
      b[int(ipivot[i])] = b[i]
      for j in range(i): sum -= a[i][j]*b[j]
      b[i] = sum

   for i in range(n-1,-1,-1):                                    # solves Ux = y
      sum = b[i]
      for j in range(i+1,n): sum -= a[i][j]*b[j]
      b[i] = sum/a[i][i]

In [27]:
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])
aa=np.copy(a)    #deep copy of an array
bb=np.copy(b)    #deep copy of an array
ipivot=np.zeros(4)
de=LUFactor(a,ipivot,4)
LUSystem(a,ipivot,b,4)
print(b)

print(np.dot(aa,b)-bb)

[ 0.1729798  -0.87689394  4.13194444 -1.9084596 ]
[  0.00000000e+00   0.00000000e+00   0.00000000e+00  -7.10542736e-15]


In [28]:
#============================================================================
def GaussSeidel(a, b, x, n, init):
# Copy right, code from Titus textbook. 
#----------------------------------------------------------------------------
#  Solves linear system a x = b by the Gauss-Seidel method.
#  Convergence is ensure by left-multiplying the system with a^T.
#  a    - coefficient matrix (n x n)
#  b    - vector of constant terms
#  x    - initial approximation of solution (input); solution (output)
#  n    - order of system
#  err  - maximum relative error of the solution components
#  init - initialization option: 0 - refines initial approximation 
#                                1 - initializes solution
#----------------------------------------------------------------------------
   eps = 1e-15                                 # relative precision criterion
   itmax = 10000                                    # max no. of iterations

   s = [[0]*(n) for i in range(n)]           # matrices of reduced system
   t = [0]*(n)

   for i in range(n):                         # matrices of normal system
      for j in range(i+1):                      # by multiplication with aT
         s[i][j] = 0e0                            # store result in s and t
         for k in range(n): s[i][j] += a[k][i]*a[k][j]
         s[j][i] = s[i][j]

      t[i] = 0e0
      for j in range(n): t[i] += a[j][i]*b[j]

   for i in range(n):                # matrices s and t of reduced system
      f = -1e0/s[i][i]; t[i] /= s[i][i]
      for j in range(n): s[i][j] *= f

   if (init):
      for i in range(n): x[i] = t[i]                # initialize solution

   for k in range(itmax):                            # loop of iterations
      err = 0e0
      for i in range(n):
         delta = t[i]                                            # correction
         for j in range(n): delta += s[i][j]*x[j]
         x[i] += delta                        # new approximation to solution
         if (x[i]): delta /= x[i]                            # relative error
         if (np.fabs(delta) > err): err = np.fabs(delta)            # maximum error
       #  print('delta,err',delta,err)
            
      if (err <= eps): break                              # check convergence

   if (k > itmax-2): print("GaussSeidel: max. no. of iterations exceeded !")
    
   return err

In [29]:
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])
x=np.array([1.,1.,1.,1.])

GaussSeidel(a, b, x, 4, 1)
print('x=',x)
print(np.dot(a,x)-b)

x= [ 0.1729798  -0.87689394  4.13194444 -1.9084596 ]
[  9.23705556e-14   6.75015599e-14  -2.27373675e-13  -3.19744231e-14]


In [34]:
import numpy as np
import time
N=100
A=np.zeros((N,N),float)
B=np.zeros(N,float)
for i in range(N):
    for j in range(N):
        A[i,j]=1./(i+j+1.)
        
for i in range(N):
    B[i]=1./(i+1)

start = time.time()
# write one line of code to solve Ax=B using linalg package 
x=np.linalg.solve(A,B)
end = time.time()
print('x=',x)
print('Time ',end-start)

x=np.ones(N)
start2 = time.time()
# write one line of code to solve Ax=B using Gauss-Siedel method 
GaussSeidel(A, B, x, 4, 1)

end2 = time.time()
print('x=',x)
print('Time ',end2-start2)

ipivot=np.zeros(N)
start3 = time.time()
# write two lines of code to solve Ax=B with LU decomposition
de=LUFactor(A,ipivot,4)
LUSystem(A,ipivot,B,4)

end3 = time.time()
print('x=',B)
print('Time ',end3-start3)

x= [ 1.  0.  0.  0.  0.  0.  0.  0. -0. -0. -0.  0.  0.  0. -0.  0. -0. -0.
  0.  0.  0. -0.  0.  0.  0. -0. -0. -0.  0.  0. -0.  0. -0.  0.  0.  0.
 -0. -0. -0.  0. -0. -0. -0.  0. -0. -0. -0.  0.  0. -0.  0.  0.  0.  0.
 -0.  0. -0.  0.  0.  0. -0.  0. -0. -0.  0.  0.  0. -0. -0.  0. -0. -0.
  0.  0. -0. -0.  0.  0. -0. -0.  0. -0. -0. -0.  0. -0. -0.  0.  0.  0.
 -0.  0.  0. -0. -0.  0. -0. -0. -0. -0.]
Time  0.0004706382751464844
GaussSeidel: max. no. of iterations exceeded !
x= [ 1.0297499  -0.04694805 -0.26420505  0.32845104  1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          1.          1.          1.
  1.          1.          1.          1.          

In [36]:
# Find the eigenvalue and eigenvector for ([1,-3,3],[3,-5,3],[6,-6,4])

# Now double check that the derived eigenvalue and eigenvector can satisfy Ax=\lamba x

import numpy as np
I=np.array([[1,-3,3],[3,-5,3],[6,-6,4]])
print(I)
eigenvalues, eigenmatrix = np.linalg.eig(I)
print('Eigenvalues', eigenvalues, '\n Eigenmatrix', eigenmatrix)
print('Eigenvector',eigenmatrix[:,0],eigenmatrix[:,1])

eigenvector1=np.array([eigenmatrix[0,0],eigenmatrix[1,0],eigenmatrix[2,0]])
LHS = np.dot(I,eigenvector1)
RHS = eigenvector1*eigenvalues[0]
print('LHS-RHS',LHS-RHS)

[[ 1 -3  3]
 [ 3 -5  3]
 [ 6 -6  4]]
Eigenvalues [ 4. +0.00000000e+00j -2. +1.10465796e-15j -2. -1.10465796e-15j] 
 Eigenmatrix [[-0.40824829+0.j          0.24400118-0.40702229j  0.24400118+0.40702229j]
 [-0.40824829+0.j         -0.41621909-0.40702229j -0.41621909+0.40702229j]
 [-0.81649658+0.j         -0.66022027+0.j         -0.66022027-0.j        ]]
Eigenvector [-0.40824829+0.j -0.40824829+0.j -0.81649658+0.j] [ 0.24400118-0.40702229j -0.41621909-0.40702229j -0.66022027+0.j        ]
LHS-RHS [  4.44089210e-16+0.j   2.22044605e-16+0.j   8.88178420e-16+0.j]
